/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <bits/stdc++.h>

using namespace std;

class A {
public:
  void solve(istream& in, ostream& out) {
    int n;
    in >> n;
    out << n;
  }
};

int main() {
  ios_base::sync_with_stdio(false);
  cin.tie(nullptr);
  A solver;
  std::istream& in(std::cin);
  std::ostream& out(std::cout);
  solver.solve(in, out);
  return 0;
}